# Generated by Django 3.2 on 2021-04-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(max_length=120)),
                ('email', models.TextField(max_length=120)),
                ('address', models.TextField(max_length=255)),
            ],
        ),
    ]
