# Generated by Django 3.2 on 2021-04-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='students',
            name='full_name',
            field=models.CharField(max_length=120),
        ),
    ]
